//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC_SP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Practik1282Entities : DbContext
    {
        public Practik1282Entities()
            : base("name=Practik1282Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card_work> Card_work { get; set; }
        public virtual DbSet<Consumer> Consumer { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Material_card> Material_card { get; set; }
        public virtual DbSet<Nomencloture> Nomencloture { get; set; }
        public virtual DbSet<OKEI> OKEI { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Passport_data> Passport_data { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Rationing_groups> Rationing_groups { get; set; }
        public virtual DbSet<Stamp> Stamp { get; set; }
        public virtual DbSet<Structure> Structure { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Work_piece> Work_piece { get; set; }
        public virtual DbSet<Workshop> Workshop { get; set; }
    }
}
