//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC_SP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport_data
    {
        public int Code_empl { get; set; }
        public string Serial { get; set; }
        public string Number { get; set; }
        public System.DateTime Date_birth { get; set; }
        public string Address { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
