//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC_SP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public int Num_provider { get; set; }
        public int Num_workshop { get; set; }
        public string Name { get; set; }
    
        public virtual Workshop Workshop { get; set; }
    }
}
